---
title: "Analysis"
output: html_document
date: "2023-11-25"
---

```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(broom)

output_trips <- read_delim("output_trips.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

output_legs <- read_delim("output_legs.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

drt_customer_stats_drt <- read_delim("drt_customer_stats_drt.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
drt_detailed_distanceStats_drt <- read_delim("drt_detailed_distanceStats_drt.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
drt_vehicle_stats_drt <- read_delim("drt_vehicle_stats_drt.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
database <- read_csv("C:/Users/MATSIM/Downloads/database.csv")
# ValidationTrips <- read_csv("UrbanContextTrainingData.csv")
# database <- database[database$ind_tripID %in% ValidationTrips$ind_tripID, ]
# Update the "choice" column based on conditions
Mesh <- read.csv("Mesh.csv")
database <- merge(database, Mesh, by = "ind_tripID", all = FALSE)

databse <- database %>%
    filter(is.na(CHOICE_FAC)) 

database <- database %>% 
  mutate(UrbanIndex = case_when(
    PC1 > 4.91 ~ "CBD",
    PC1 < 4.91 & PC1 > 1.57 ~ "Urban",
    PC1 < 1.57 & PC1 > -2.35 ~ "Suburban",
    PC1 < -2.35  ~ "Rural",
    TRUE ~ NA
  ))

database$CHOICE_FAC <- ifelse(database$repMode_type3_fac == "bus", "bus", 
                    ifelse(database$repMode_type3_fac == "car" & database$car_driver_fac == "passenger", "ride", database$CHOICE_FAC))


df <- select(database, ind_tripID, costIC, costCAR, repMode_type2_fac, id_ind, tripDurationMin, CHOICE, CHOICE_FAC, origin , destination, time.wk, time.s,time.in.traffic.s, time.bk, time, access_time.w, depart_time.w, PC1, UrbanIndex)
df$time.r = (df$time + df$access_time.w + df$depart_time.w)/60
df$time.wk = (df$time.wk)/60
df$time.bk = (df$time.bk)/60
df$time.s = (df$time.s)/60
df$time.in.traffic.s = (df$time.in.traffic.s)/60

df <- df %>%
  rename(person  = ind_tripID)

result_df <- inner_join(df, output_trips, by = "person")
result_df <- result_df %>%
  mutate(SimulatedTimeMinutes = as.integer(substr(trav_time, 1, 2)) * 60 + as.integer(substr(trav_time, 4, 5))) %>%
  rename(ActualTimeMinutes  = tripDurationMin) 

outliers <- result_df %>%
    filter(ActualTimeMinutes >= 150 |SimulatedTimeMinutes >= 250)


result_df <- result_df %>%
    filter(ActualTimeMinutes <= 150) %>%
    filter(SimulatedTimeMinutes <= 250) %>%
  mutate(longest_distance_mode = case_when(
    longest_distance_mode == NA ~ "other",
    TRUE ~ longest_distance_mode
  ))

# Plot actual vs simulated travel times with CHOICE_FAC coloring
ggplot(result_df, aes(x = SimulatedTimeMinutes, y = ActualTimeMinutes, color = CHOICE_FAC)) +
  geom_point(alpha = 0.5) +  # Set transparency to see overlapping points
  geom_abline(intercept = 0, slope = 1, color = "blue", linetype = "dashed") +  # Line of equality
  geom_smooth(method = "lm", color = "red") +  # Linear model fit line
  labs(
    x = "Simulated Travel Time",
    y = "Actual Travel Time",
    color = "Choice Factor"
  ) +
  ggtitle("Comparison of Actual vs Simulated Travel Times") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  theme(
    plot.title = element_text(hjust = 0.5),  # Center the plot title
    legend.position = "bottom"  # Adjust legend position
  )


# Count the occurrences of each mode
data_longest <- result_df %>%
  group_by(longest_distance_mode) %>%
  summarise(Count = n())
data_choice <- result_df %>%
  group_by(CHOICE_FAC) %>%
  summarise(Count = n())
data_choice$CHOICE_FAC[9] <- "other"

data_longest$longest_distance_mode <- factor(data_longest$longest_distance_mode,
                                             levels = c("walk", "bike", "car", "pt", "ride", "drt"))
# data_longest$longest_distance_mode <- factor(data_longest$longest_distance_mode,
#                                              levels = c("walk", "bike", "car", "pt", "ride"))
data_choice$CHOICE_FAC <- factor(data_choice$CHOICE_FAC,
                                 levels = c("Walk", "Bike", "Car", "Train_walk", "Train_bike", "Train_car", "ride", "bus","other"))
# Rename levels to match: Match 'Train_*' with 'pt'
levels(data_choice$CHOICE_FAC)[levels(data_choice$CHOICE_FAC) == "Train_walk"] <- "pt"
levels(data_choice$CHOICE_FAC)[levels(data_choice$CHOICE_FAC) == "Train_bike"] <- "pt"
levels(data_choice$CHOICE_FAC)[levels(data_choice$CHOICE_FAC) == "Train_car"] <- "pt"
levels(data_choice$CHOICE_FAC)[levels(data_choice$CHOICE_FAC) == "Bike"] <- "bike"
levels(data_choice$CHOICE_FAC)[levels(data_choice$CHOICE_FAC) == "Walk"] <- "walk"
levels(data_choice$CHOICE_FAC)[levels(data_choice$CHOICE_FAC) == "Car"] <- "car"

# Combine the two datasets
combined_data <- bind_rows(
  mutate(data_longest, Category = "SimulatedModeShare"),
  mutate(data_choice, Category = "ActualModeShare"))
combined_data$longest_distance_mode <- factor(combined_data$longest_distance_mode,
                                             levels = c("bike", "car", "drt", "pt", "ride", "walk", "other", "bus"))
# combined_data$longest_distance_mode <- factor(combined_data$longest_distance_mode,
#                                              levels = c("bike", "car", "pt", "ride", "walk", "other", "bus"))
# combined_data$longest_distance_mode[5] <- combined_data$CHOICE_FAC[5]
# combined_data$longest_distance_mode[6] <- combined_data$CHOICE_FAC[6]
# combined_data$longest_distance_mode[7] <- combined_data$CHOICE_FAC[7]
combined_data$longest_distance_mode[8] <- combined_data$CHOICE_FAC[8]
combined_data$longest_distance_mode[9] <- combined_data$CHOICE_FAC[9]
combined_data$longest_distance_mode[10] <- combined_data$CHOICE_FAC[10]
combined_data$longest_distance_mode[11] <- combined_data$CHOICE_FAC[11]
combined_data$longest_distance_mode[12] <- combined_data$CHOICE_FAC[12]
combined_data$longest_distance_mode[13] <- combined_data$CHOICE_FAC[13]
combined_data$longest_distance_mode[14] <- combined_data$CHOICE_FAC[14]
combined_data$longest_distance_mode[15] <- combined_data$CHOICE_FAC[15]
combined_data$longest_distance_mode[16] <- combined_data$CHOICE_FAC[16]
# combined_data$Count[2] <- 6795

# combined_data <- subset(combined_data, !(rownames(combined_data) == 15))
# combined_data <- subset(combined_data, !(rownames(combined_data) == 13))

combined_data <- combined_data %>%
  group_by(Category) %>%
  mutate(Percentage = Count / sum(Count)) %>%
  ungroup()

ggplot(combined_data, aes(x = Category, y = Percentage, fill = longest_distance_mode)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(aes(label = scales::percent(Percentage)), position = position_stack(vjust = 0.5), size = 3) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Actual Mode Share vs Simulated Mode Share", x = "Category", y = "Percentage Share") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()

order_longest_distance_mode <- c("walk", "bike", "ride", "car", "pt", "bus", "drt", "other")
order_CHOICE_FAC <- c("Walk", "Bike", "ride", "Car", "Train_walk", "Train_bike", "Train_car", "bus","other")

result_df$longest_distance_mode <- factor(
  result_df$longest_distance_mode,
  levels = order_longest_distance_mode
)

result_df$CHOICE_FAC <- factor(
  result_df$CHOICE_FAC,
  levels = order_CHOICE_FAC
)

result_df <- result_df %>%
  filter(!is.na(CHOICE_FAC)) %>%
  filter(!is.na(UrbanIndex)) %>%
  mutate(UrbanIndex = factor(UrbanIndex, levels = c("CBD", "Urban", "Suburban", "Rural")))

ggplot(result_df, aes(x = UrbanIndex, fill = CHOICE_FAC)) +
  geom_bar(position = "fill") +
  labs(title = "Actual Mode Share vs Simulated Mode Share ", 
       x = "Category", y = "Proportion") +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal()
ggplot(result_df %>% filter(!is.na(longest_distance_mode)), aes(x = UrbanIndex, fill = longest_distance_mode)) +
  geom_bar(position = "fill") +
  labs(title = "Actual Mode Share vs Simulated Mode Share ", x = "Category", y = "Proportion") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()
ggplot(result_df %>% filter(!is.na(longest_distance_mode)), aes(x = UrbanIndex, fill = longest_distance_mode)) +
  geom_bar() +
  labs(title = "Actual Mode Share vs Simulated Mode Share", x = "Category", y = "Count") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()
ggplot(result_df , aes(x = UrbanIndex, fill = CHOICE_FAC)) +
  geom_bar() +
  labs(title = "Actual Mode Share vs Simulated Mode Share", x = "Category", y = "Count") +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal()


result_df1 <- result_df %>%
     filter(SimulatedTimeMinutes <= 250) %>%
    filter(time.r <= 250) %>%
   filter(longest_distance_mode == "pt" )

ggplot(result_df1, aes(x = UrbanIndex, fill = longest_distance_mode)) +
  geom_bar() +
  labs(title = "Actual Mode Share vs Simulated Mode Share", x = "Category", y = "Count") +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal()

# Fit a linear model
lm_model <- lm(time.r ~ SimulatedTimeMinutes, data = result_df1)

# Calculate R-squared value
lm_summary <- summary(lm_model)
r_squared <- lm_summary$r.squared

# Calculate Mean Squared Error
mse <- mean(lm_model$residuals^2)

# Plot with R-squared annotation
ggplot(result_df1, aes(x = SimulatedTimeMinutes, y = time.r, color = modes)) +
  geom_point(alpha = 0.5) +
  geom_abline(intercept = 0, slope = 1, color = "blue", linetype = "dashed") +
  geom_smooth(method = "lm", color = "red") +
  labs(
    x = "Simulated Travel Time",
    y = "Actual Travel Time",
    color = "Choice Factor"
  ) +
  ggtitle("Comparison of Actual vs Simulated Travel Times") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "bottom"
  ) +
  annotate("text", x = Inf, y = Inf, hjust = 1.1, vjust = 2,
           label = sprintf("R² = %.2f, MSE = %.2f", r_squared, mse),
           color = "black", size = 3.5)

ggplot(result_df1, aes(x = ActualTimeMinutes, y = time.r, color = modes)) +
  geom_point(alpha = 0.5) +
  geom_abline(intercept = 0, slope = 1, color = "blue", linetype = "dashed") +
  geom_smooth(method = "lm", color = "red") +
  labs(
    x = "Reported Travel Time",
    y = "Actual Travel Time",
    color = "Choice Factor"
  ) +
  ggtitle("Comparison of Actual vs Reported Travel Times") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set3") +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "bottom"
  ) +
  annotate("text", x = Inf, y = Inf, hjust = 1.1, vjust = 2,
           label = sprintf("R² = %.2f, MSE = %.2f", r_squared, mse),
           color = "black", size = 3.5)

result_df1 <- result_df1 %>%
  mutate(CHOICE_FAC = if_else(is.na(CHOICE_FAC), "Other", CHOICE_FAC))

# Create a bar chart with fill based on "Category2"
ggplot(result_df1, aes(x = modes   , fill = CHOICE_FAC)) +
  geom_bar() +
  labs(
    x = "Category1",
    y = "Count",
    title = "Access/Egress Modes for transit "
  ) +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Filter the data frame
filtered_df <- result_df1 %>%
  filter(SimulatedTimeMinutes <= 300)

# Now create the boxplot with the filtered data
ggplot(filtered_df, aes(x = modes, y = SimulatedTimeMinutes)) + 
  geom_boxplot() +
  labs(x = "Mode of Transport", y = "Travel Time (minutes)") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

accessdrttrps <- result_df %>%
  filter((modes == "walk-pt-walk" | modes == "walk-pt-walk-pt-walk") & longest_distance_mode == "pt" )


ggplot(accessdrttrps, aes(x = modes   , fill = CHOICE_FAC)) +
  geom_bar(position = "fill") +
  labs(
    x = "Category1",
    y = "Count",
    title = "Access/Egress Modes for transit "
  ) +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


ggplot(accessdrttrps, aes(x = UrbanIndex, fill = CHOICE_FAC)) +
  geom_bar() +
  labs(title = "Actual Mode Share for Access/Egress ", x = "Category", y = "Count") +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal()
ggplot(accessdrttrps, aes(x = UrbanIndex, fill = CHOICE_FAC)) +
  geom_bar(position = "fill") +  # This will count the number of rows for each UrbanIndex
  labs(title = "Actual Mode Share for Access/Egress", x = "Category", y = "Proportion") +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal()
ggplot(accessdrttrps, aes(x = UrbanIndex, fill = longest_distance_mode)) +
  geom_bar() +
  labs(title = "Simulated Mode Share for Access/Egress", x = "Category", y = "Count") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()
ggplot(accessdrttrps, aes(x = PC1, fill = CHOICE_FAC)) +
  geom_density(position = "stack") +
  scale_y_continuous(labels = scales::comma) +
  labs(title = "Simulated Mode Share for Access/Egress", x = "Category", y = "Count") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()
ggplot(accessdrttrps, aes(x = PC1, fill = CHOICE_FAC)) +
  geom_density(position = "fill") +
  scale_y_continuous(labels = scales::comma) +
  labs(title = "Actual Mode Share vs Simulated Mode Share", x = "Category", y = "Count") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()

# Filter out "bus" and "other" categories
filtered_data <- combined_data %>%
  filter(longest_distance_mode != "bus" & longest_distance_mode != "other")

filtered_data <- filtered_data %>%
  group_by(Category) %>%
  mutate(Percentage = Count / sum(Count)) %>%
  ungroup()

ggplot(filtered_data, aes(x = Category, y = Percentage, fill = longest_distance_mode)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(aes(label = scales::percent(Percentage)), position = position_stack(vjust = 0.5), size = 3) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Actual Mode Share vs Simulated Mode Share", x = "Category", y = "Percentage Share") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()


```

```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(broom)

output_trips <- read_delim("output_trips.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

output_legs <- read_delim("output_legs.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

database <- read_csv("C:/Users/MATSIM/Downloads/Nov1_Trips.csv")

Mesh <- read.csv("TripsbyUrbanIndex.csv")
database <- merge(database, Mesh, by = "ind_tripID", all = FALSE)
ValidationTrips <- read_csv("UrbanContextTrainingData.csv")
database <- database[database$ind_tripID %in% ValidationTrips$ind_tripID, ]
database <- database %>% 
  mutate(UrbanIndex = case_when(
    PC1.x > 8.5 ~ "CBD",
    PC1.x < 8.5 & PC1.x > 3.0 ~ "Urban",
    PC1.x < 3.0 & PC1.x > -1.5  ~ "Suburban",
    PC1.x < -1.5   ~ "Rural",
    TRUE ~ NA
  ))

database <- database %>%
  mutate(CHOICE_FAC = ifelse(repMode_type2 == 6, "walk",
               ifelse(repMode_type2 == 5, "bike",
               ifelse(repMode_type2 == 3 & car_driver == 1, "car",
               ifelse(repMode_type2 == 3 & car_driver == 2 & hh_license == 1 & (hh_myCar == 1 | hh_myCar == 2), "ride",
               ifelse(repMode_type2 == 3 & car_driver == 2 & (hh_license == 2 | hh_license == 3 |hh_myCar == 3), "ride",
               ifelse(repMode_type2 == 1, "pt",
               ifelse(repMode_type2 == 2, "bus",
               ifelse(repMode_type1 == 9, "taxi",
               "other"
               )))))))))

databse <- database %>%
    filter(is.na(CHOICE_FAC)) 


df <- select(database, ind_tripID,  repMode_type2_fac, id_ind, tripDurationMin, CHOICE_FAC,  PC1.x, UrbanIndex)

df <- df %>%
  rename(person  = ind_tripID)

result_df <- inner_join(df, output_trips, by = "person")

data_longest <- result_df %>%
  group_by(longest_distance_mode) %>%
  summarise(Count = n())
data_choice <- result_df %>%
  group_by(CHOICE_FAC) %>%
  summarise(Count = n())
data_choice$CHOICE_FAC[8] <- "other"

data_longest$longest_distance_mode <- factor(data_longest$longest_distance_mode,
                                             levels = c("walk", "bike", "car", "pt", "ride", "drt"))

data_choice$CHOICE_FAC <- factor(data_choice$CHOICE_FAC,
                                 levels = c("walk", "bike", "car", "pt", "ride", "drt", "bus", "other"))

combined_data <- bind_rows(
  mutate(data_longest, Category = "SimulatedModeShare"),
  mutate(data_choice, Category = "ActualModeShare"))
combined_data$longest_distance_mode <- factor(combined_data$longest_distance_mode,
                                             levels = c("bike", "car", "drt", "pt", "ride", "walk", "other", "bus"))

# combined_data$longest_distance_mode[5] <- combined_data$CHOICE_FAC[5]
# combined_data$longest_distance_mode[6] <- combined_data$CHOICE_FAC[6]
combined_data$longest_distance_mode[7] <- combined_data$CHOICE_FAC[7]
combined_data$longest_distance_mode[8] <- combined_data$CHOICE_FAC[8]
combined_data$longest_distance_mode[9] <- combined_data$CHOICE_FAC[9]
combined_data$longest_distance_mode[10] <- combined_data$CHOICE_FAC[10]
combined_data$longest_distance_mode[11] <- combined_data$CHOICE_FAC[11]
combined_data$longest_distance_mode[12] <- combined_data$CHOICE_FAC[12]
combined_data$longest_distance_mode[13] <- combined_data$CHOICE_FAC[13]
combined_data$longest_distance_mode[14] <- combined_data$CHOICE_FAC[14]
# combined_data$longest_distance_mode[15] <- combined_data$CHOICE_FAC[15]

combined_data <- combined_data %>%
  group_by(Category) %>%
  mutate(Percentage = Count / sum(Count)) %>%
  ungroup()

ggplot(combined_data, aes(x = Category, y = Percentage, fill = longest_distance_mode)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(aes(label = scales::percent(Percentage)), position = position_stack(vjust = 0.5), size = 3) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Actual Mode Share vs Simulated Mode Share", x = "Category", y = "Percentage Share") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()

filtered_data <- combined_data %>%
  filter(longest_distance_mode != "bus" & longest_distance_mode != "other")

filtered_data <- filtered_data %>%
  group_by(Category) %>%
  mutate(Percentage = Count / sum(Count)) %>%
  ungroup()

ggplot(filtered_data, aes(x = Category, y = Percentage, fill = longest_distance_mode)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(aes(label = scales::percent(Percentage)), position = position_stack(vjust = 0.5), size = 3) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Actual Mode Share vs Simulated Mode Share", x = "Category", y = "Percentage Share") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()

order_ldm <- c("walk", "bike", "ride", "car", "pt", "bus", "drt", "other")
order_CHOICE_FAC <- c("walk", "bike", "ride", "car", "pt", "bus", "drt", "other")

result_df$longest_distance_mode <- factor(result_df$longest_distance_mode, levels = order_ldm)

result_df$CHOICE_FAC <- factor( result_df$CHOICE_FAC, levels = order_CHOICE_FAC  )

result_df <- result_df %>%
  filter(!is.na(CHOICE_FAC)) %>%
  filter(!is.na(UrbanIndex)) %>%
  mutate(UrbanIndex = factor(UrbanIndex, levels = c("CBD", "Urban", "Suburban", "Rural")))

result_df2 <- result_df %>%
  filter(CHOICE_FAC != "bus" & CHOICE_FAC != "other") %>%
  group_by(UrbanIndex, CHOICE_FAC) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  ungroup() %>% # Remove the grouping
  group_by(UrbanIndex) %>%
  mutate(Percentage = Count / sum(Count)) %>%
  ungroup()

result_df3 <- result_df %>%
  group_by(UrbanIndex, longest_distance_mode) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  ungroup() %>% # Remove the grouping
  group_by(UrbanIndex) %>%
  mutate(Percentage = Count / sum(Count)) %>%
  ungroup()

ggplot(result_df2, aes(x = UrbanIndex, y = Count, fill = CHOICE_FAC)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(aes(label = scales::percent(Percentage, accuracy = 1)),position = position_fill(vjust = 0.5),
            size = 3, check_overlap = TRUE) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Actual Mode Share by Built Environment", 
       x = "Category", y = "Proportion") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()

ggplot(result_df3, aes(x = UrbanIndex, y = Count, fill = longest_distance_mode)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(aes(label = scales::percent(Percentage, accuracy = 1)),position = position_fill(vjust = 0.5),
            size = 3, check_overlap = TRUE) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Simulated Mode Share by Built Environment", 
       x = "Category", y = "Proportion") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal()



```



```{r}
# 
# X100_drt_alightments_drt <- read_delim("30.drt_alightments_drt.csv", 
#     delim = ";", escape_double = FALSE, trim_ws = TRUE)
# X100_drt_boardings_drt <- read_delim("30.drt_boardings_drt.csv", 
#     delim = ";", escape_double = FALSE, trim_ws = TRUE)
# X100_drt_detours_drt <- read_delim("30.drt_detours_drt.csv", 
#     delim = ";", escape_double = FALSE, trim_ws = TRUE)

x20_vehicleDistanceStats_drt <- read_delim("20.vehicleDistanceStats_drt.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
x20_waitStats_drt <- read_delim("20.waitStats_drt.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
X20_waitTimeComparison_drt <- read_delim("20.waitTimeComparison_drt.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
x20_drt_idleVehiclesPerZoneXY <- read_delim("20.drt_idleVehiclesPerZoneXY.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
x20_waitStats_drt_zonal <- read_delim("20.waitStats_drt_zonal.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
x20_drt_legs_drt <- read_delim("20.drt_legs_drt.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
x20_drt_idleVehiclesPerZoneXY <- read_delim("20.drt_idleVehiclesPerZoneXY.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

drtdemand <- sum(x20_waitStats_drt_zonal$nRequests)

```




